### DISCUSSION TITLE
devai new config format and model_aliases

### DISCUSSION THREAD

**Discussion by jeremychone** [aipack-ai/aipack#36] [Announcements]
I updated the config.toml format to make it simpler, which will allow us to add some powerful functionality in the future.

## New Way

So, the new format is as follows:

```toml
[default_options]
model = "gpt-4o-mini" # or an alias below (e.g. "fast", "cost-saver")
temperature = 0.0
input_concurrency = 6

model_aliases = { fast = "gemini-2.0-flash-001", cost-saver = "deepseek-chat", thinker = "o3-mini-high"}
```

Also, now, instead of having `# Config` to override some config properties in the `.devai` file, we have `# Options`, which is just the options. For example:

``````md
# Options
```toml
model = "fast"
temperature = 0.5
```
``````

The goal of this new format is to:

- Flatten all of the agent options properties so that it is simpler to override them at different levels (e.g., `# Options`).
- Make it clear in the `config.toml` that those are options that can be overridden.

And I took the opportunity to implement the cool `model_aliases = {alias_name = model_name}` functionality.

## Legacy Way

The legacy `config.toml` looked like this:

```toml
[genai]
model = "gemini-2.0-flash-exp"
temperature = 0.0

[runtime]
input_concurrency = 6
```

and in the `.devai`:

``````md

# Config

```toml
[genai]
model = "gpt-4o"
```

**Comment by davehorner** [comment]
did we break a standard toml file with a custom extension?  making specialized toml format or is that toml? if it isn't toml, I'd suggest a new extension? .dtoml and support both forms via merge with .dtoml taking precedence?  idk maybe that's toml.

**Reply by jeremychone** [reply]
It's completely valid toml. I am not planning to add break the toml, lua, or any code block / file extensions.

**Reply by jeremychone** [reply]
Single line object is allowed in toml. You can also do the model_aliases as 
```toml
[default_options.model_aliases]
fast = "gemini-2.0-flash-001"
cost-saver = "deepseek-chat"
standard = "gpt-4o"
coder = "claude-3-5-sonnet-20241022"
thinker = "o3-mini-high"
```

Both are valid toml.
